"""custo pct imposto embutido por linha

Revision ID: 111b3c1a8e87
Revises: ff825da42c0e
Create Date: 2026-09-04 11:41:04.873028
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '111b3c1a8e87'
down_revision: Union[str, None] = 'ff825da42c0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custo_empresa', sa.Column('pct_imposto_embutido', sa.Numeric(precision=9, scale=6), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custo_empresa', 'pct_imposto_embutido')
    # ### end Alembic commands ###
