"""usuario foto de perfil

Revision ID: 13bf9c29c602
Revises: b0c9c6d4aa09
Create Date: 2026-08-31 11:42:17.998264
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '13bf9c29c602'
down_revision: Union[str, None] = 'b0c9c6d4aa09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('foto_nome', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'foto_nome')
    # ### end Alembic commands ###
