"""estrutura inicial

Revision ID: b0c9c6d4aa09
Revises: 
Create Date: 2026-08-20 17:32:57.980658
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b0c9c6d4aa09'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.Enum('ESCRITORIO', 'EMPRESA', name='tipotenant', native_enum=False, length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cenario_aliquota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('aliquota_ibs', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('aliquota_cbs', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('fonte', sa.String(length=255), nullable=True),
    sa.Column('data_publicacao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('base_legal', sa.String(length=255), nullable=True),
    sa.Column('tipo', sa.Enum('OFICIAL', 'TRAVA_LEGAL', 'USUARIO', name='tipocenario', native_enum=False, length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('substituido_por_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['substituido_por_id'], ['cenario_aliquota.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cenario_aliquota_tenant_id'), 'cenario_aliquota', ['tenant_id'], unique=False)
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('razao_social', sa.String(length=255), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('municipio', sa.String(length=120), nullable=False),
    sa.Column('cnae_principal', sa.String(length=7), nullable=True),
    sa.Column('ramo', sa.String(length=120), nullable=True),
    sa.Column('regime', sa.Enum('SIMPLES', 'PRESUMIDO', 'REAL', name='regimetributario', native_enum=False, length=20), nullable=False),
    sa.Column('simples_anexo', sa.Integer(), nullable=True),
    sa.Column('simples_opcao_ibs_cbs', sa.Enum('UNICO', 'HIBRIDO', name='opcaosimplesibscbs', native_enum=False, length=20), nullable=True),
    sa.Column('faturamento_anual', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('rbt12', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('pct_interno', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('pct_interestadual', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('pct_exportacao', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('pct_consumidor_final', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('margem_bruta', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('margem_liquida', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('aliq_icms', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('aliq_iss', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('aliq_pis', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('aliq_cofins', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('aliq_ipi', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('pct_compras_com_credito', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('beneficios_fiscais', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criada_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizada_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('faturamento_anual >= 0', name='ck_empresa_faturamento'),
    sa.CheckConstraint('simples_anexo is null or simples_anexo between 1 and 5', name='ck_empresa_simples_anexo'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_empresa_tenant_cnpj', 'empresa', ['tenant_id', 'cnpj'], unique=False)
    op.create_index(op.f('ix_empresa_tenant_id'), 'empresa', ['tenant_id'], unique=False)
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('papel', sa.Enum('ADMIN', 'GESTOR', 'OPERADOR', name='papelusuario', native_enum=False, length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('ultimo_acesso', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_usuario_email')
    )
    op.create_index(op.f('ix_usuario_tenant_id'), 'usuario', ['tenant_id'], unique=False)
    op.create_table('custo_empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('origem', sa.Enum('MERCADORIAS', 'INSUMOS', 'SERVICOS_TOMADOS', 'ENERGIA', 'FRETE', 'ALUGUEL', 'FOLHA', 'OUTROS', name='origemcusto', native_enum=False, length=30), nullable=False),
    sa.Column('valor_anual', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('pct_fornecedor_simples', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('gera_credito_hoje', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custo_empresa_empresa_id'), 'custo_empresa', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_custo_empresa_tenant_id'), 'custo_empresa', ['tenant_id'], unique=False)
    op.create_table('item_empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('ncm', sa.String(length=8), nullable=True),
    sa.Column('codigo_servico', sa.String(length=20), nullable=True),
    sa.Column('pct_faturamento', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('aliq_icms', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('aliq_iss', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('aliq_pis', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('aliq_cofins', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('aliq_ipi', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('cst_ibs_cbs', sa.String(length=3), nullable=True),
    sa.Column('c_class_trib', sa.String(length=6), nullable=True),
    sa.Column('regime_diferenciado', sa.String(length=60), nullable=True),
    sa.Column('sujeito_imposto_seletivo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_empresa_empresa_id'), 'item_empresa', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_item_empresa_tenant_id'), 'item_empresa', ['tenant_id'], unique=False)
    op.create_table('log_auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('acao', sa.String(length=80), nullable=False),
    sa.Column('entidade', sa.String(length=80), nullable=True),
    sa.Column('entidade_id', sa.Integer(), nullable=True),
    sa.Column('detalhe', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_auditoria_criado_em'), 'log_auditoria', ['criado_em'], unique=False)
    op.create_index(op.f('ix_log_auditoria_tenant_id'), 'log_auditoria', ['tenant_id'], unique=False)
    op.create_table('regras_versao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('versao', sa.String(length=40), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('parametros', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('vigencia_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('vigencia_fim', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('criada_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('criada_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['criada_por_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('versao', name='uq_regras_versao')
    )
    op.create_table('simulacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=True),
    sa.Column('ano_base', sa.Integer(), nullable=False),
    sa.Column('dados_informados', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('cenario_aliquota_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('regras_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('motor_versao', sa.String(length=40), nullable=False),
    sa.Column('resultado', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('carga_atual_rs', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('carga_futura_rs', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('diferenca_rs', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('diferenca_pct', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('margem_liquida_depois', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('opcao_simples', sa.Enum('UNICO', 'HIBRIDO', name='opcaosimplesibscbs', native_enum=False, length=20), nullable=True),
    sa.Column('grupo_comparacao', sa.String(length=36), nullable=True),
    sa.Column('cenario_aliquota_id', sa.Integer(), nullable=True),
    sa.Column('regras_versao_id', sa.Integer(), nullable=True),
    sa.Column('criada_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('criada_por_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('ano_base between 2026 and 2033', name='ck_simulacao_ano'),
    sa.ForeignKeyConstraint(['cenario_aliquota_id'], ['cenario_aliquota.id'], ),
    sa.ForeignKeyConstraint(['criada_por_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['regras_versao_id'], ['regras_versao.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulacao_criada_em'), 'simulacao', ['criada_em'], unique=False)
    op.create_index('ix_simulacao_empresa', 'simulacao', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_simulacao_grupo_comparacao'), 'simulacao', ['grupo_comparacao'], unique=False)
    op.create_index('ix_simulacao_tenant_criada', 'simulacao', ['tenant_id', 'criada_em'], unique=False)
    op.create_index(op.f('ix_simulacao_tenant_id'), 'simulacao', ['tenant_id'], unique=False)
    op.create_table('analise_ia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('simulacao_id', sa.Integer(), nullable=False),
    sa.Column('modelo', sa.String(length=80), nullable=False),
    sa.Column('prompt_enviado', sa.Text(), nullable=False),
    sa.Column('resposta_bruta', sa.Text(), nullable=False),
    sa.Column('resposta_renderizada', sa.Text(), nullable=True),
    sa.Column('verificacao', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status_verificacao', sa.Enum('APROVADA', 'REPROVADA', 'NAO_EXECUTADA', name='statusverificacao', native_enum=False, length=20), nullable=False),
    sa.Column('tokens_entrada', sa.Integer(), nullable=True),
    sa.Column('tokens_saida', sa.Integer(), nullable=True),
    sa.Column('custo_estimado', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('latencia_ms', sa.Integer(), nullable=True),
    sa.Column('criada_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['simulacao_id'], ['simulacao.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('simulacao_id')
    )
    op.create_index(op.f('ix_analise_ia_tenant_id'), 'analise_ia', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analise_ia_tenant_id'), table_name='analise_ia')
    op.drop_table('analise_ia')
    op.drop_index(op.f('ix_simulacao_tenant_id'), table_name='simulacao')
    op.drop_index('ix_simulacao_tenant_criada', table_name='simulacao')
    op.drop_index(op.f('ix_simulacao_grupo_comparacao'), table_name='simulacao')
    op.drop_index('ix_simulacao_empresa', table_name='simulacao')
    op.drop_index(op.f('ix_simulacao_criada_em'), table_name='simulacao')
    op.drop_table('simulacao')
    op.drop_table('regras_versao')
    op.drop_index(op.f('ix_log_auditoria_tenant_id'), table_name='log_auditoria')
    op.drop_index(op.f('ix_log_auditoria_criado_em'), table_name='log_auditoria')
    op.drop_table('log_auditoria')
    op.drop_index(op.f('ix_item_empresa_tenant_id'), table_name='item_empresa')
    op.drop_index(op.f('ix_item_empresa_empresa_id'), table_name='item_empresa')
    op.drop_table('item_empresa')
    op.drop_index(op.f('ix_custo_empresa_tenant_id'), table_name='custo_empresa')
    op.drop_index(op.f('ix_custo_empresa_empresa_id'), table_name='custo_empresa')
    op.drop_table('custo_empresa')
    op.drop_index(op.f('ix_usuario_tenant_id'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_empresa_tenant_id'), table_name='empresa')
    op.drop_index('ix_empresa_tenant_cnpj', table_name='empresa')
    op.drop_table('empresa')
    op.drop_index(op.f('ix_cenario_aliquota_tenant_id'), table_name='cenario_aliquota')
    op.drop_table('cenario_aliquota')
    op.drop_table('tenant')
    # ### end Alembic commands ###
