"""pct imposto embutido custos

Revision ID: ff825da42c0e
Revises: 13bf9c29c602
Create Date: 2026-09-02 09:53:23.844682
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ff825da42c0e'
down_revision: Union[str, None] = '13bf9c29c602'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresa', sa.Column('pct_imposto_embutido_custos', sa.Numeric(precision=9, scale=6), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empresa', 'pct_imposto_embutido_custos')
    # ### end Alembic commands ###
